// Auto-generated by Routify
export default {
  isLayout: true,
  isFallback: false,
  isIndex: false,
  isFile: true,
  file: '../src/pages/_layout.svelte',
  name: '_layout',
  id: '_layout',
  module: () => import('../src/pages/_layout.svelte'),
  meta: {},
  children: [
    {
      isLayout: false,
      isFallback: false,
      isIndex: true,
      isFile: true,
      file: '../src/pages/index.svelte',
      name: 'index',
      id: '_layout_index',
      module: () => import('../src/pages/index.svelte'),
      meta: {},
      children: []
    },
    {
      isLayout: false,
      isFallback: false,
      isIndex: false,
      isFile: true,
      file: '../src/pages/login.svelte',
      name: 'login',
      id: '_layout_login',
      module: () => import('../src/pages/login.svelte'),
      meta: {},
      children: []
    },
    {
      isLayout: false,
      isFallback: false,
      isIndex: false,
      isFile: true,
      file: '../src/pages/register.svelte',
      name: 'register',
      id: '_layout_register',
      module: () => import('../src/pages/register.svelte'),
      meta: {},
      children: []
    },
    {
      isLayout: false,
      isFallback: false,
      isIndex: false,
      isFile: true,
      file: '../src/pages/dashboard.svelte',
      name: 'dashboard',
      id: '_layout_dashboard',
      module: () => import('../src/pages/dashboard.svelte'),
      meta: { auth: true },
      children: []
    },
    {
      isLayout: false,
      isFallback: false,
      isIndex: false,
      isFile: true,
      file: '../src/pages/[username].svelte',
      name: '_username',
      id: '_layout__username',
      module: () => import('../src/pages/[username].svelte'),
      meta: {},
      children: []
    }
  ]
};
